### ISSUE TITLE
Cannot load newer Excel file format into mapper

### ISSUE THREAD

**Issue by djcomlab** [ISA-tools/ISAcreator#317]
While investigating #316 I noticed that the example data file given in that issue could not be loaded by the mapper (although this doesn't seem to be the same problem reported in that issue).

When loading an .xls file in the mapper, you get a splash graphic saying there's an error, and get this stacktrace:

```
jxl.read.biff.BiffException: Unable to recognize OLE stream
	at jxl.read.biff.CompoundFile.<init>(CompoundFile.java:116)
	at jxl.read.biff.File.<init>(File.java:127)
	at jxl.Workbook.getWorkbook(Workbook.java:221)
	at jxl.Workbook.getWorkbook(Workbook.java:198)
	at org.isatools.isacreator.formatmappingutility.loader.ExcelFileLoader.processFile(ExcelFileLoader.java:74)
```

It seems JXL does not support reading newer Excel files. A workaround is to convert the input xls into a regular csv file.

**Comment by djcomlab** [comment]
The problem is that JXL does not support the latest Excel file format - workaround is to re-save the file as older Excel 97-2003 or CSV.

**Comment by djcomlab** [comment]
The effort required retrofit to support for .xslx is too great, given the simple enough workaround. Will add as a known issue to release notes, and close.
