### ISSUE TITLE
Java 11 compatibility issue

### ISSUE THREAD

**Issue by DanBerrios** [ISA-tools/ISAcreator#337]
It doesn't seem like ISACreator 1.7.11 runs without errors using Java 11.  I tried 1.7.11 and 1.7.10 without success.

**Comment by jgranduel** [comment]
Hi, 

probably due to missing `com.sun.awt.AWTUtilities` which was removed in Java 11.

```
> java --version
openjdk 11.0.12 2021-07-20
OpenJDK Runtime Environment GraalVM CE 21.2.0 (build 11.0.12+6-jvmci-21.2-b08)
OpenJDK 64-Bit Server VM GraalVM CE 21.2.0 (build 11.0.12+6-jvmci-21.2-b08, mixed mode, sharing)

> java -jar .\ISAcreator.jar

Launching ISAcreator Application...
[...]\AppData\Local\Temp\isacreator.servicebase18222848183496990636.tmp
Loaded the following system packages:
org.isatools.isacreator.plugins,uk.ac.ebi.utils.xml,uk.ac.ebi.utils.io,uk.ac.ebi.utils.xml,org.isatools.isacreator.ontologymanager.common,org.isatools.isacreator.ontologymanager,org.isatools.isacreator.io.importisa,org.isatools.isacreator.plugins.registries,org.isatools.isacreator.plugins.host.service,org.isatools.isacreator.configuration.io,org.isatools.isacreator.model,org.isatools.isacreator.api.utils,org.isatools.isacreator.spreadsheet.model,org.isatools.isacreator.managers,org.isatools.isacreator.gui,org.isatools.isacreator.common,org.isatools.errorreporter.ui,org.apache.xmlbeans,org.apache.log4j,org.apache.log4j.spi,org.isatools.isatab.configurator.schema,org.isatools.isacreator.effects,org.isatools.isacreator.spreadsheet,org.isatools.isacreator.apiutils,org.isatools.isacreator.configuration,org.isatools.errorreporter.ui.borders,com.sun.awt,uk.ac.ebi.utils.collections,org.jdesktop.fuse,org.isatools.isacreator.gui.menu,org.isatools.isatab.isaconfigurator,com.explodingpixels.macwidgets,org.isatools.isacreator.io.importisa.errorhandling.exceptions,org.apache.commons.logging,org.isatools.isacreator.ontologyselectiontool,org.apache.commons.collections15,org.apache.commons.collections15.multimap,org.isatools.macros.plugin.workflowvisualization.graph,org.apache.commons.collections15.set,org.isatools.isacreator.visualization.tree,org.isatools.isacreator.effects.borders,org.isatools.errorreporter.model,org.isatools.isacreator.autofilteringlist,org.isatools.errorreporter.ui.utils,org.apache.commons.collections15.map,org.isatools.isacreator.common.CustomMenuItemUI,javax.swing,javax.swing.text,javax.swing.tree,javax.swing.table,javax.swing.event,javax.swing.border,javax.management,javax.naming,javax.crypto,javax.crypto.spec,javax.net.ssl,javax.security.auth.x500,javax.xml.transform.dom,javax.xml.transform.stream,javax.xml.parsers,javax.xml.datatype,javax.xml.xpath,javax.xml.transform,javax.xml.transform.sax,javax.xml.validation,javax.xml.namespace,org.w3c.dom,org.w3c.dom.traversal,org.w3c.dom.ranges,org.w3c.dom.ls,org.w3c.dom.events,org.xml.sax,org.xml.sax.ext,org.xml.sax.helpers,org.ietf.jgss
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.apache.felix.framework.util.SecureAction (file:[...]/isacreator-1.7.11/ISAcreator.jar) to method java.net.URLClassLoader.addURL(java.net.URL)
WARNING: Please consider reporting this to the maintainers of org.apache.felix.framework.util.SecureAction
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
Creating GUI
Exception in thread "AWT-EventQueue-0" java.lang.NoClassDefFoundError: com/sun/awt/AWTUtilities
        at org.isatools.isacreator.gui.modeselection.ModeSelector.createGUI(ModeSelector.java:91)
Starting up OSGi framework....  at org.isatools.isacreator.gui.modeselection.ModeSelector.access$1000(ModeSelector.java:57)

        at org.isatools.isacreator.gui.modeselection.ModeSelector$5.run(ModeSelector.java:236)
        at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
        at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
        at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:740)
        at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
        at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
Caused by: java.lang.ClassNotFoundException: com.sun.awt.AWTUtilities
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
        ... 16 more
```

Any update to be expected soon?

**Comment by GakenouOF** [comment]
I get this same error with java 17 and 18. Is there any solution to this yet @jgranduel?

**Comment by ghost** [comment]
Also getting this issue in java 18, any solutions?
